config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  get 'account', to: 'dashboard#index', as: 'dashboard'
  get 'api/events', to: 'api#events'
  get 'about', to: 'home#about', as: :about
  get 'fellowship', to: 'home#fellowship', as: :fellowship
  get 'visit', to: 'home#visit', as: :visit
  get 'study-with-us', to: 'home#study_with_us', as: :study_with_us
  get 'faculty', to: 'home#faculty', as: :faculty
  get 'residency', to: 'home#residency', as: :residency
  get 'residents', to: 'home#residents', as: :residents
  get 'scholarships', to: 'home#scholarships', as: :scholarships
  get 'donate', to: redirect('https://donate.stripe.com/cN25lPeUe3qO5zyfYY'), as: :donate_redirect
  get 'shop', to: redirect('https://nwspk.myshopify.com/'), as: :shop
  get 'feedback', to: redirect('https://forms.gle/NLZ8JQdDFeuToWgF6'), as: :feedback
  get 'rationclub', to: redirect('https://forms.gle/T3rXorsrb4gXKazv9'), as: :rationclub
  get 'library', to: 'home#library', as: :library
  get 'jobs', to: 'home#jobs', as: :jobs
  
  get '2023', to: 'home#course2023', as: :course2023
  
  get '2024', to: 'home#course2024', as: :course2024
  
  get '2025', to: 'home#course2025', as: :course2025
  get 'fieldwork25', to: redirect('https://docs.google.com/document/d/19eLJIlsOuKmC0sMlSqC-C8gGmI9XIOtS_8jQ5pHBuWc'), as: :fieldwork25
  get 'pairwork25', to: redirect('https://docs.google.com/document/d/1ZSf8g-G3rbklbpEDq_WFCykOUy921ZQwb9YZvFPbhbw'), as: :pairwork25 

  post 'webhooks', to: 'webhooks#index'

  # LCPT routes
  get 'lcpt', to: 'lcpt#index', as: :lcpt

  resource :subscription, only: [:edit, :update, :destroy] do
    get :checkout
    get :process_card
  end

  resource :user, only: [:edit, :update]
  resources :events, only: :index

  devise_for :users, path: 'account', controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'membership', to: 'users/registrations#new'
    post 'create-checkout-session', to: 'subscriptions#create_checkout_session', as: :create_checkout_session
    post 'customer-portal', to: 'subscriptions#customer_portal', as: :customer_portal
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'home#index'

  get '*unmatched_route', to: 'application#route_not_found', constraints: { format: :html }
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan

  validates :plan_id, presence: true, on: :create

  scope :with_credit_card, -> { where.not(customer_id: '') }
  scope :active, -> { where.not(subscription_id: '', active_until: nil) }

  def active?
    subscription_id.present? && !active_until.nil? && active_until > Time.zone.now
  end

  def grace_period?
    !active_until.nil? && active_until < Time.zone.now
  end

  def needs_checkout?
    customer_id.blank?
  end

  def plan_name
    plan.try(:name)
  end

  after_save :set_user_role

  private

  def set_user_role
    return unless active? && user.applicant?

    user.update(role: User::ROLES[:member])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout 'subpage'
  before_action :authenticate_user!
  before_action :set_subscription
  before_action :require_selected_plan!

  def create_checkout_session
    begin
      session = Stripe::Checkout::Session.create(
        {
          mode: 'subscription',
          customer_email: current_user.email,
          line_items: [
            {
              quantity: 1,
              price: @subscription.plan.stripe_id,
              tax_rates: [STRIPE_TAX_RATE_ID]
            }
          ],
          success_url: "#{CANONICAL_URL}#{process_card_subscription_path}?session_id={CHECKOUT_SESSION_ID}",
          cancel_url: "#{CANONICAL_URL}#{process_card_subscription_path}"
        }
      )
    rescue StandardError => e
      response = { error: { message: e.error.message } }.to_json
      render json: response, status: :bad_request
    end

    redirect_to session.url, status: :see_other
  end

  def customer_portal
    session = Stripe::BillingPortal::Session.create(
      {
        customer: @subscription.customer_id,
        return_url: "#{CANONICAL_URL}#{dashboard_path}"
      }
    )

    redirect_to session.url, status: :see_other
  end

  def checkout
    @plan = @subscription.plan
    redirect_to dashboard_path if @plan.nil?
  end

  def edit; end

  def update
    new_plan_id = params[:subscription][:plan_id] if params[:subscription]

    if @subscription.plan_id != new_plan_id && Plan.exists?(new_plan_id.to_i)
      service = ChangePlanService.new
      service.call(@subscription, new_plan_id)

      redirect_to dashboard_path, notice: "Successfully changed subscription plan to #{@subscription.plan.name}"
    else
      redirect_to edit_subscription_path, alert: 'No change was made since the same plan was selected'
    end
  end

  def destroy
    service = TerminateSubscriptionService.new
    service.call(@subscription)

    redirect_to dashboard_path, notice: 'Your subscription has been successfully terminated'
  end

  def process_card
    stripe_session_id = params[:session_id]

    return if stripe_session_id.blank?

    checkout = Stripe::Checkout::Session.retrieve(stripe_session_id)
    @subscription.customer_id = checkout.customer
    @subscription.subscription_id = checkout.subscription

    stripe_subscription = Stripe::Subscription.retrieve(@subscription.subscription_id)
    @subscription.active_until = Time.zone.at(stripe_subscription.current_period_end).to_fs(:db)
    @subscription.save!

    AdminMailer.new_subscriber_email(current_user).deliver_later

    redirect_to dashboard_path, notice: 'Congratulations!'
  end

  private

  def set_subscription
    @subscription = current_user.subscription
  end

  def require_selected_plan!
    redirect_to(dashboard_path, alert: 'You do not have selected a plan to check out with') if @subscription.nil?
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/checkout.html.haml
- content_for :page_title do
  Checkout

- content_for :back_link do
  = dashboard_path

- if @subscription.customer_id.blank?
  %h2 Become a member
  %p
    One last step before you're a full member with a subscription! You need to checkout with Stripe.

- else
  %h2 Change credit card
  %p Just click on the button below and enter your new credit card details into the Stripe form.

- if @subscription.customer_id.blank?
  = simple_form_for(@subscription, url: create_checkout_session_path, method: :post) do |f|
    %button{:id => "checkout-and-portal-button", :type => :submit} Checkout
- else
  = simple_form_for(@subscription, url: customer_portal_path, method: :post) do |f|
    %button{:id => "checkout-and-portal-button", :type => :submit} Change card

app/views/subscriptions/edit.html.haml
- content_for :page_title do
  Change plan

- content_for :back_link do
  = dashboard_path

%h3.no-topping Change subscription plan

- if @subscription.needs_checkout?
  .alert.alert-info
    It looks like you haven't checked out yet. You need to checkout to be an active member of Newspeak House. You can change your plan selection before proceeding.
    %strong= link_to 'Checkout now', checkout_subscription_path

= simple_form_for(@subscription, url: subscription_path) do |f|
  = f.association :plan, collection: Plan.all_visible, label_method: :description, include_blank: false

  .form-group
    = f.button :submit, 'Change plan'

- unless @subscription.needs_checkout?
  %h3 Change credit card

  %p
    Click
    = link_to 'here', checkout_subscription_path
    to change your credit card that is being billed.

- if @subscription.active?
  %h3 Cancel subscription
  %p
    Click
    = link_to 'here', subscription_path, data: { confirm: 'Are you sure?' }, method: :delete
    to cancel.